//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FilmActor = newFilmActorTable("sakila", "film_actor", "")

type filmActorTable struct {
	mysql.Table

	// Columns
	ActorID    mysql.ColumnInteger
	FilmID     mysql.ColumnInteger
	LastUpdate mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FilmActorTable struct {
	filmActorTable

	NEW filmActorTable
}

// AS creates new FilmActorTable with assigned alias
func (a FilmActorTable) AS(alias string) *FilmActorTable {
	return newFilmActorTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FilmActorTable with assigned schema name
func (a FilmActorTable) FromSchema(schemaName string) *FilmActorTable {
	return newFilmActorTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FilmActorTable with assigned table prefix
func (a FilmActorTable) WithPrefix(prefix string) *FilmActorTable {
	return newFilmActorTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FilmActorTable with assigned table suffix
func (a FilmActorTable) WithSuffix(suffix string) *FilmActorTable {
	return newFilmActorTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFilmActorTable(schemaName, tableName, alias string) *FilmActorTable {
	return &FilmActorTable{
		filmActorTable: newFilmActorTableImpl(schemaName, tableName, alias),
		NEW:            newFilmActorTableImpl("", "new", ""),
	}
}

func newFilmActorTableImpl(schemaName, tableName, alias string) filmActorTable {
	var (
		ActorIDColumn    = mysql.IntegerColumn("actor_id")
		FilmIDColumn     = mysql.IntegerColumn("film_id")
		LastUpdateColumn = mysql.TimestampColumn("last_update")
		allColumns       = mysql.ColumnList{ActorIDColumn, FilmIDColumn, LastUpdateColumn}
		mutableColumns   = mysql.ColumnList{LastUpdateColumn}
	)

	return filmActorTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ActorID:    ActorIDColumn,
		FilmID:     FilmIDColumn,
		LastUpdate: LastUpdateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
