//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FilmText = newFilmTextTable("sakila", "film_text", "")

type filmTextTable struct {
	mysql.Table

	// Columns
	FilmID      mysql.ColumnInteger
	Title       mysql.ColumnString
	Description mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FilmTextTable struct {
	filmTextTable

	NEW filmTextTable
}

// AS creates new FilmTextTable with assigned alias
func (a FilmTextTable) AS(alias string) *FilmTextTable {
	return newFilmTextTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FilmTextTable with assigned schema name
func (a FilmTextTable) FromSchema(schemaName string) *FilmTextTable {
	return newFilmTextTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FilmTextTable with assigned table prefix
func (a FilmTextTable) WithPrefix(prefix string) *FilmTextTable {
	return newFilmTextTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FilmTextTable with assigned table suffix
func (a FilmTextTable) WithSuffix(suffix string) *FilmTextTable {
	return newFilmTextTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFilmTextTable(schemaName, tableName, alias string) *FilmTextTable {
	return &FilmTextTable{
		filmTextTable: newFilmTextTableImpl(schemaName, tableName, alias),
		NEW:           newFilmTextTableImpl("", "new", ""),
	}
}

func newFilmTextTableImpl(schemaName, tableName, alias string) filmTextTable {
	var (
		FilmIDColumn      = mysql.IntegerColumn("film_id")
		TitleColumn       = mysql.StringColumn("title")
		DescriptionColumn = mysql.StringColumn("description")
		allColumns        = mysql.ColumnList{FilmIDColumn, TitleColumn, DescriptionColumn}
		mutableColumns    = mysql.ColumnList{TitleColumn, DescriptionColumn}
	)

	return filmTextTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		FilmID:      FilmIDColumn,
		Title:       TitleColumn,
		Description: DescriptionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
