//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FilmCategory = newFilmCategoryTable("sakila", "film_category", "")

type filmCategoryTable struct {
	mysql.Table

	// Columns
	FilmID     mysql.ColumnInteger
	CategoryID mysql.ColumnInteger
	LastUpdate mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FilmCategoryTable struct {
	filmCategoryTable

	NEW filmCategoryTable
}

// AS creates new FilmCategoryTable with assigned alias
func (a FilmCategoryTable) AS(alias string) *FilmCategoryTable {
	return newFilmCategoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FilmCategoryTable with assigned schema name
func (a FilmCategoryTable) FromSchema(schemaName string) *FilmCategoryTable {
	return newFilmCategoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FilmCategoryTable with assigned table prefix
func (a FilmCategoryTable) WithPrefix(prefix string) *FilmCategoryTable {
	return newFilmCategoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FilmCategoryTable with assigned table suffix
func (a FilmCategoryTable) WithSuffix(suffix string) *FilmCategoryTable {
	return newFilmCategoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFilmCategoryTable(schemaName, tableName, alias string) *FilmCategoryTable {
	return &FilmCategoryTable{
		filmCategoryTable: newFilmCategoryTableImpl(schemaName, tableName, alias),
		NEW:               newFilmCategoryTableImpl("", "new", ""),
	}
}

func newFilmCategoryTableImpl(schemaName, tableName, alias string) filmCategoryTable {
	var (
		FilmIDColumn     = mysql.IntegerColumn("film_id")
		CategoryIDColumn = mysql.IntegerColumn("category_id")
		LastUpdateColumn = mysql.TimestampColumn("last_update")
		allColumns       = mysql.ColumnList{FilmIDColumn, CategoryIDColumn, LastUpdateColumn}
		mutableColumns   = mysql.ColumnList{LastUpdateColumn}
	)

	return filmCategoryTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		FilmID:     FilmIDColumn,
		CategoryID: CategoryIDColumn,
		LastUpdate: LastUpdateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
