//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Language = newLanguageTable("sakila", "language", "")

type languageTable struct {
	mysql.Table

	// Columns
	LanguageID mysql.ColumnInteger
	Name       mysql.ColumnString
	LastUpdate mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type LanguageTable struct {
	languageTable

	NEW languageTable
}

// AS creates new LanguageTable with assigned alias
func (a LanguageTable) AS(alias string) *LanguageTable {
	return newLanguageTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LanguageTable with assigned schema name
func (a LanguageTable) FromSchema(schemaName string) *LanguageTable {
	return newLanguageTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LanguageTable with assigned table prefix
func (a LanguageTable) WithPrefix(prefix string) *LanguageTable {
	return newLanguageTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LanguageTable with assigned table suffix
func (a LanguageTable) WithSuffix(suffix string) *LanguageTable {
	return newLanguageTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLanguageTable(schemaName, tableName, alias string) *LanguageTable {
	return &LanguageTable{
		languageTable: newLanguageTableImpl(schemaName, tableName, alias),
		NEW:           newLanguageTableImpl("", "new", ""),
	}
}

func newLanguageTableImpl(schemaName, tableName, alias string) languageTable {
	var (
		LanguageIDColumn = mysql.IntegerColumn("language_id")
		NameColumn       = mysql.StringColumn("name")
		LastUpdateColumn = mysql.TimestampColumn("last_update")
		allColumns       = mysql.ColumnList{LanguageIDColumn, NameColumn, LastUpdateColumn}
		mutableColumns   = mysql.ColumnList{NameColumn, LastUpdateColumn}
	)

	return languageTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		LanguageID: LanguageIDColumn,
		Name:       NameColumn,
		LastUpdate: LastUpdateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
