//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Rental = newRentalTable("sakila", "rental", "")

type rentalTable struct {
	mysql.Table

	// Columns
	RentalID    mysql.ColumnInteger
	RentalDate  mysql.ColumnTimestamp
	InventoryID mysql.ColumnInteger
	CustomerID  mysql.ColumnInteger
	ReturnDate  mysql.ColumnTimestamp
	StaffID     mysql.ColumnInteger
	LastUpdate  mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type RentalTable struct {
	rentalTable

	NEW rentalTable
}

// AS creates new RentalTable with assigned alias
func (a RentalTable) AS(alias string) *RentalTable {
	return newRentalTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RentalTable with assigned schema name
func (a RentalTable) FromSchema(schemaName string) *RentalTable {
	return newRentalTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RentalTable with assigned table prefix
func (a RentalTable) WithPrefix(prefix string) *RentalTable {
	return newRentalTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RentalTable with assigned table suffix
func (a RentalTable) WithSuffix(suffix string) *RentalTable {
	return newRentalTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRentalTable(schemaName, tableName, alias string) *RentalTable {
	return &RentalTable{
		rentalTable: newRentalTableImpl(schemaName, tableName, alias),
		NEW:         newRentalTableImpl("", "new", ""),
	}
}

func newRentalTableImpl(schemaName, tableName, alias string) rentalTable {
	var (
		RentalIDColumn    = mysql.IntegerColumn("rental_id")
		RentalDateColumn  = mysql.TimestampColumn("rental_date")
		InventoryIDColumn = mysql.IntegerColumn("inventory_id")
		CustomerIDColumn  = mysql.IntegerColumn("customer_id")
		ReturnDateColumn  = mysql.TimestampColumn("return_date")
		StaffIDColumn     = mysql.IntegerColumn("staff_id")
		LastUpdateColumn  = mysql.TimestampColumn("last_update")
		allColumns        = mysql.ColumnList{RentalIDColumn, RentalDateColumn, InventoryIDColumn, CustomerIDColumn, ReturnDateColumn, StaffIDColumn, LastUpdateColumn}
		mutableColumns    = mysql.ColumnList{RentalDateColumn, InventoryIDColumn, CustomerIDColumn, ReturnDateColumn, StaffIDColumn, LastUpdateColumn}
	)

	return rentalTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		RentalID:    RentalIDColumn,
		RentalDate:  RentalDateColumn,
		InventoryID: InventoryIDColumn,
		CustomerID:  CustomerIDColumn,
		ReturnDate:  ReturnDateColumn,
		StaffID:     StaffIDColumn,
		LastUpdate:  LastUpdateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
