//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/mysql"
)

var SalesByFilmCategory = newSalesByFilmCategoryTable("sakila", "sales_by_film_category", "")

type salesByFilmCategoryTable struct {
	mysql.Table

	// Columns
	Category   mysql.ColumnString
	TotalSales mysql.ColumnFloat

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type SalesByFilmCategoryTable struct {
	salesByFilmCategoryTable

	NEW salesByFilmCategoryTable
}

// AS creates new SalesByFilmCategoryTable with assigned alias
func (a SalesByFilmCategoryTable) AS(alias string) *SalesByFilmCategoryTable {
	return newSalesByFilmCategoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SalesByFilmCategoryTable with assigned schema name
func (a SalesByFilmCategoryTable) FromSchema(schemaName string) *SalesByFilmCategoryTable {
	return newSalesByFilmCategoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SalesByFilmCategoryTable with assigned table prefix
func (a SalesByFilmCategoryTable) WithPrefix(prefix string) *SalesByFilmCategoryTable {
	return newSalesByFilmCategoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SalesByFilmCategoryTable with assigned table suffix
func (a SalesByFilmCategoryTable) WithSuffix(suffix string) *SalesByFilmCategoryTable {
	return newSalesByFilmCategoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSalesByFilmCategoryTable(schemaName, tableName, alias string) *SalesByFilmCategoryTable {
	return &SalesByFilmCategoryTable{
		salesByFilmCategoryTable: newSalesByFilmCategoryTableImpl(schemaName, tableName, alias),
		NEW:                      newSalesByFilmCategoryTableImpl("", "new", ""),
	}
}

func newSalesByFilmCategoryTableImpl(schemaName, tableName, alias string) salesByFilmCategoryTable {
	var (
		CategoryColumn   = mysql.StringColumn("category")
		TotalSalesColumn = mysql.FloatColumn("total_sales")
		allColumns       = mysql.ColumnList{CategoryColumn, TotalSalesColumn}
		mutableColumns   = mysql.ColumnList{CategoryColumn, TotalSalesColumn}
	)

	return salesByFilmCategoryTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Category:   CategoryColumn,
		TotalSales: TotalSalesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
