//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type City struct {
	CityID     uint16 `sql:"primary_key"`
	City       string
	CountryID  uint16
	LastUpdate time.Time
}
