//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Country struct {
	CountryID  uint16 `sql:"primary_key"`
	Country    string
	LastUpdate time.Time
}
