//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Customer struct {
	CustomerID uint16 `sql:"primary_key"`
	StoreID    uint8
	FirstName  string
	LastName   string
	Email      *string
	AddressID  uint16
	Active     bool
	CreateDate time.Time
	LastUpdate *time.Time
}
