//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type FilmRating string

const (
	FilmRating_G    FilmRating = "G"
	FilmRating_Pg   FilmRating = "PG"
	FilmRating_Pg13 FilmRating = "PG-13"
	FilmRating_R    FilmRating = "R"
	FilmRating_Nc17 FilmRating = "NC-17"
)

func (e *FilmRating) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "G":
		*e = FilmRating_G
	case "PG":
		*e = FilmRating_Pg
	case "PG-13":
		*e = FilmRating_Pg13
	case "R":
		*e = FilmRating_R
	case "NC-17":
		*e = FilmRating_Nc17
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for FilmRating enum")
	}

	return nil
}

func (e FilmRating) String() string {
	return string(e)
}
