//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type FilmText struct {
	FilmID      int16 `sql:"primary_key"`
	Title       string
	Description *string
}
