//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Inventory struct {
	InventoryID uint32 `sql:"primary_key"`
	FilmID      uint16
	StoreID     uint8
	LastUpdate  time.Time
}
