//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Payment struct {
	PaymentID   uint16 `sql:"primary_key"`
	CustomerID  uint16
	StaffID     uint8
	RentalID    *int32
	Amount      float64
	PaymentDate time.Time
	LastUpdate  *time.Time
}
