//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Staff struct {
	StaffID    uint8 `sql:"primary_key"`
	FirstName  string
	LastName   string
	AddressID  uint16
	Picture    *[]byte
	Email      *string
	StoreID    uint8
	Active     bool
	Username   string
	Password   *string
	LastUpdate time.Time
}
