//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Store struct {
	StoreID        uint8 `sql:"primary_key"`
	ManagerStaffID uint8
	AddressID      uint16
	LastUpdate     time.Time
}
